import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
const url = process.argv[2]
if (!url) throw new Error('Pass the managed preview URL')
const browser = await chromium.launch({headless:true})
try {
  const page = await browser.newPage({viewport:{width:1280,height:900}})
  const errors=[]; page.on('pageerror',e=>errors.push(e.message))
  page.on('console', message => { if(message.type() === 'error') console.log('Browser error:', message.text()) })
  // No network account or real customer data: make this an isolated demo browser.
  await page.route('**/*', route => {
    const request=route.request(), path=new URL(request.url()).pathname
    if (/^\/(auth|me|floorplans|billing|analytics|report-error)(\/|$)/.test(path)) return route.fulfill({status:404,contentType:'text/html',body:'No API in isolated browser test'})
    return route.continue()
  })
  await page.goto(url)
  await page.getByRole('button',{name:'Sign in',exact:true}).first().click()
  await page.locator('.auth-admin').click()
  await page.waitForSelector('.dashboard')
  await page.getByRole('button',{name:'New floorplan',exact:true}).click()
  await page.waitForSelector('canvas')
  const snapshot={version:2,activeFloor:1,floors:[{walls:[{id:1,closed:false,points:[{x:0,y:0},{x:80,y:0},{x:80,y:80}]}],cameras:[],objects:[{id:2,presetId:'safe',x:35,y:45,rotation:90}],wires:[]},{walls:[],cameras:[{id:3,x:40,y:30,rotation:45,hFov:90,distance:8}],objects:[],wires:[{id:4,points:[{x:1,y:2},{x:5,y:6}]}]}]}
  await page.evaluate(s=>window.__mmcSetSnapshot(s),snapshot)
  await page.waitForTimeout(1100)
  await page.getByRole('button',{name:'Save & Dashboard',exact:true}).click()
  await page.getByRole('button',{name:'Open',exact:true}).click()
  const reopened=await page.evaluate(()=>window.__mmcGetSnapshot())
  assert.deepEqual(reopened.floors[0], snapshot.floors[0]); assert.deepEqual(reopened.floors[1],snapshot.floors[1])
  console.log('✓ all-floor edits survive Dashboard exit and reopen')
  await page.evaluate(()=>{
    const s=window.__mmcGetSnapshot(); s.floors[1].cameras[0].x=123; window.__mmcSetSnapshot(s)
  })
  await page.waitForTimeout(100)
  await page.reload()
  await page.getByRole('button',{name:'Open',exact:true}).click()
  assert.equal((await page.evaluate(()=>window.__mmcGetSnapshot())).floors[1].cameras[0].x,123)
  console.log('✓ browser autosave survives reload before cloud debounce')
  await page.getByRole('button',{name:'Save & Dashboard',exact:true}).click()
  page.once('dialog', dialog=>dialog.accept('Renamed house'))
  await page.getByRole('button',{name:'Rename',exact:true}).click()
  await page.getByText('Renamed house',{exact:true}).waitFor({state:'attached'})
  console.log('Name geometry:', await page.locator('.fp-name').evaluate(n=>({box:n.getBoundingClientRect().toJSON(),style:getComputedStyle(n).display})))
  await page.getByRole('button',{name:'Duplicate',exact:true}).click()
  await page.getByText('Renamed house (copy)',{exact:true}).waitFor({state:'attached'})
  page.once('dialog', dialog=>dialog.accept())
  await page.locator('.fp-row').filter({hasText:'(copy)'}).getByRole('button',{name:'Delete',exact:true}).click()
  await page.getByText('Renamed house (copy)',{exact:true}).waitFor({state:'detached'})
  console.log('✓ rename, duplicate and confirmed delete work through the dashboard')
  await page.getByRole('button',{name:'Open',exact:true}).click()
  await page.getByRole('button',{name:'Tools',exact:true}).click()
  await page.locator('.cam-card').filter({has:page.locator('.cam-name', {hasText:/^Wall$/})}).click()
  const canvas=page.locator('canvas'); const box=await canvas.boundingBox()
  for (const [x,y] of [[90,110],[190,110],[190,210]]) await page.mouse.click(box.x+x,box.y+y)
  await page.getByRole('button',{name:'Finish Wall',exact:true}).click()
  const drawn=(await page.evaluate(()=>window.__mmcGetSnapshot())).floors[1].walls.at(-1)
  assert.equal(drawn.closed,false);assert.equal(drawn.points.length,3)
  console.log('✓ three mouse clicks finish as an open L, not a triangle')
  await page.getByRole('button',{name:'Select',exact:true}).click()
  await page.evaluate(()=>window.__mmcSetSnapshot({version:3,activeFloor:0,floors:[{walls:[{id:101,closed:true,points:[{x:0,y:0},{x:160,y:0},{x:160,y:160},{x:0,y:160}]}],cameras:[],objects:[],wires:[]}]}))
  await page.waitForTimeout(100)
  await page.getByRole('button',{name:'Reset View',exact:true}).click()
  const currentBox=await canvas.boundingBox()
  await page.mouse.click(currentBox.x+currentBox.width/2+80,currentBox.y+currentBox.height/2)
  page.once('dialog',dialog=>dialog.accept('4'))
  await page.getByRole('button',{name:'Calibrate scale',exact:true}).click()
  assert.equal((await page.evaluate(()=>window.__mmcGetSnapshot())).floors[0].walls[0].points[1].x,320)
  await page.getByRole('button',{name:/Undo/}).click()
  assert.equal((await page.evaluate(()=>window.__mmcGetSnapshot())).floors[0].walls[0].points[1].x,160)
  console.log('✓ measured calibration is applied and undone through the editor')
  assert.deepEqual(errors,[])
  await page.screenshot({path:'node_modules/.cache/planner-save.png',fullPage:true})
  console.log('✓ no runtime errors; screenshot saved')
} finally {await browser.close()}
